query myImages($page: Int) {
  myImages(page: $page) {
    total
    total_pages
    page
    hasMore
    results {
      id
      author
      url
      link
      height
      width
      likesCount
      likedBy {
        id
        name
      }
    }
  }
}
